version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    rebase-strategy: disabled
    schedule:
      interval: monthly
    assignees:
      - "NoDocCat"
    reviewers:
      - "NoDocCat"

  - package-ecosystem: npm
    directory: /
    rebase-strategy: disabled
    open-pull-requests-limit: 1
    schedule:
      interval: monthly
    assignees:
      - "NoDocCat"
    reviewers:
      - "NoDocCat"
